// app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";
import { AuthProvider } from "./Components/AuthProvider";
import Navbar from "./Components/Navbar";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Achiraya PM",
  description: "Generated by create next app",
  icons: {
    icon: "/achiraya.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">

      <body className="bg-blue-950 ml-20 rounded-2xl">
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
