import type { Metadata } from "next";

import Navbar from "./Components/Navbar";
import "./globals.css";



export const metadata: Metadata = {
  title: "Achiraya Project Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-blue-950">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
